### ISSUE TITLE
App is not working on Windows

### ISSUE THREAD

**Issue by diegoalvis** [LaCoro/ConsumerFlutterApp#75]
There's a problem when building the app apparently happening only on Windows OS check this thread for more details #71

**Comment by llanox** [comment]
I'm closing it since I could run it on Windows 10 with no problems building or deploying it. It seems the user is selecting a city without stores in the demo database; that's why the user sees a blank screen.
![demo](https://user-images.githubusercontent.com/282575/96826459-0533d700-13f9-11eb-92fc-63d55ae7c7de.png)
